### PR TITLE
set homepage to next report

### LINKED ISSUE #36: change default startpage
the default startpage should be changed into the first report.

for example
`/list/` => `/list/report/next`

### PR DESCRIPTION
**Pull request by tolry**
fixes #36

### CODE REVIEW

**Comment by DavidBadura** [comment]
that is too static. not everyone wants to have next as a starting point. we should take the first report, which was defined in the config. default it is `next`.

**Comment by tolry** [comment]
ok, will change it

**Comment by DavidBadura** [comment]
can you also remove `ListController::listAction`? :)

**Comment by tolry** [comment]
@DavidBadura done

**Comment by tolry** [comment]
Should I ignore the StyleCI checks for now or just apply the patch? Seems not fully configured to your CS yet?

**Comment by DavidBadura** [comment]
ignore StyleCI, it was only a test ;-) thank you!

**Pull request merged**
