### PR TITLE
highlight urgent tasks in list view

### LINKED ISSUE #18: highlighting urgency
indicate a task's urgency in the list view

### PR DESCRIPTION
**Pull request by tolry**
fixes #18 
- [x] highlight tasks based on urgency
- [x]  make urgency thresholds configurable
- [x] ~~fancy colors instead or red, orange, yellow?~~

### CODE REVIEW

**Comment by DavidBadura** [comment]
`fancy colors instead or red, orange, yellow?` it's okay, Sophie wants to redesign doThings :wink:

**Comment by DavidBadura** [comment]
only configuration is missing

**Comment by tolry** [comment]
first version ready for review/merge - lots of room for improvement, but an improvement to the current state none the less, I hope

**Comment by DavidBadura** [comment]
Thank you :)

**Pull request merged**
